name: Open new issue
on: 
  workflow_dispatch:
  issues:
    types:
      - closed
jobs:
  close-issue:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - run: |
          echo "issue Got closed!"
          
